version: '3.7'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql-nodejs
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ducphap0112
      MYSQL_DATABASE: notebooks
    ports:
     - "3308:3306"  
    volumes:
    # Mysql
    - db:/var/lib/mysql
    networks: 
      - nodejss

  app:
    container_name: client
    image: docker-react-i
    build: ./client
    ports:
      - "3000:3000"
      
  web:
    depends_on:
      - mysql
    build: ./
    ports: 
     - "5000:5000"
    volumes:
    - ./:/app
    restart: unless-stopped
    container_name: notebooks-typescript
    stdin_open: true
    tty: true
    networks: 
      - nodejss

volumes:
  db:

networks:
  nodejss:
